core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from customuser.views import password_email_request
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('user/password_reset/', password_email_request, name='password_reset'),
    path('user/', include('django.contrib.auth.urls')),
    path('', include('customuser.urls', namespace='customuser')),
    path('', include('company.urls', namespace='company')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('transactions.urls', namespace='transactions')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('contractors.urls', namespace='contractors')),
    path('', include('subscription.urls', namespace='subscription')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('products.urls', namespace='products')),
    path('', include('invoice.urls', namespace='invoice')),
    path('', include('integrations.urls', namespace='integrations')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customuser/urls.py
from django.urls import path
from .views import signup, signin, signout, settings, \
    password_reset_request, activate_link, email_send_success, \
    email_invalid, bad_request, deactivate_user

app_name = 'customuser'

urlpatterns = [
    path('profile/settings/', settings, name='settings'),
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('password_reset_request/', password_reset_request, name='password_reset_request'),
    path('activate/<uidb64>/<token>/', activate_link,
            name='activate'),
    path('activate-email-link/done/', email_send_success, name='email_send_success'),
    path('email-invalid-link/', email_invalid, name='email_invalid'),
    path('bad_request/', bad_request, name='bad_request'),
    path('deactivate/', deactivate_user, name='deactivate'),
]

customuser/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")
        db_table = 'auth_user'

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    email = models.EmailField(
        verbose_name=_("email address"), unique=True,
        error_messages={
            'unique': _(
                "A user is already registered with this email address"),
        },
    )
    first_name = models.CharField(
        max_length=30, verbose_name=_("first name"), blank=True,
    )
    last_name = models.CharField(
        max_length=30, verbose_name=_("last name"), blank=True,
    )
    phone_number = models.CharField(max_length=30, verbose_name=_("phone number"), blank=True
                                    )
    is_staff = models.BooleanField(
        verbose_name=_("staff status"),
        default=False,
        help_text=_(
            "Designates whether the user can log into this admin site."
        ),
    )
    is_active = models.BooleanField(
        verbose_name=_("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(
        verbose_name=_("date joined"), default=timezone.now,
    )

    user_country = models.CharField(max_length=255, blank=True, null=True)

    objects = UserManager()


class User_Account(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    default_date = models.CharField(max_length=10, blank=True, null=True)
    default_currency = models.CharField(max_length=3, blank=True, null=True)


    date_creation = models.DateTimeField(
        verbose_name=_("date_creation"), default=timezone.now,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'User Account'
        verbose_name_plural = 'Users Accounts'


class Countries(models.Model):
    country = models.CharField(max_length=255)

    def __str__(self):
        return self.country

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'


class DateFormat(models.Model):
    format = models.CharField(max_length=10)


    def __str__(self):
        return self.format


    class Meta:
        verbose_name = 'Format'
        verbose_name_plural = 'Formats'

customuser/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ModelForm
from .models import CustomUser


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email',)


class LogInForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


class CustomUserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'phone_number', 'user_country']

customuser/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site

from company.models import Currency
from .forms import SignUpForm, LogInForm, CustomUserForm
from django.contrib.auth import get_user_model
from .token import account_activation_token
from .models import User_Account, Countries, CustomUser, DateFormat


def signup(request):

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            user.is_active = False
            user.save()

            User_Account.objects.create(name=user.email, owner=user)
            current_site = get_current_site(request)

            subject = 'Activation link has been sent to your email'
            email_template_name = "registration/registration_email_confirm.txt"
            message = {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.id)),
                'token': account_activation_token.make_token(user),
            }
            email = render_to_string(email_template_name, message)
            send_mail(subject, email, 'hello@finum.online', [user, ], fail_silently=False)
            return redirect('customuser:email_send_success')
    else:
        form = SignUpForm()

    context = {'form': form}

    return render(request, 'customuser/signup.html', context)


def signin(request):

    if request.method == 'POST':
        form = LogInForm(request.POST)

        if form.is_valid():

            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                return redirect('dashboard:dashboard')
            else:
                form.add_error('email', 'Invalid input email or password data')

    else:
        form = LogInForm()

    context = {'form': form}

    return render(request, 'customuser/signin.html', context)


@login_required(login_url='/signin/')
def signout(request):
    logout(request)
    return redirect('customuser:signin')


@login_required(login_url='/signin/')
def settings(request):

    user_account = User_Account.objects.get(owner=request.user)
    countries = Countries.objects.all()
    dates = DateFormat.objects.all()
    currencies = Currency.objects.all()

    if request.method == 'POST':
        form = CustomUserForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('customuser:settings')

    else:
        form = CustomUserForm(instance=request.user)


    context = {'countries': countries, 'dates': dates, 'currencies': currencies,
               'user_account': user_account, 'form': form}

    return render(request, 'customuser/settings.html', context)


def activate_link(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('integrations:integrations')
    else:
        return redirect('customuser:email_invalid')


@login_required(login_url='/signin/')
def password_reset_request(request):
    user = request.user
    subject = "Password Reset Requested"
    email_template_name = "registration/password_reset_email.txt"
    current_site = get_current_site(request)

    c = {
        "email": user,
        'domain': current_site.domain,
        'site_name': 'Finum',
        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
        "user": user,
        'token': default_token_generator.make_token(user),
        'protocol': 'http',
    }
    email = render_to_string(email_template_name, c)
    try:
        send_mail(subject, email, 'hello@finum.online', [user, ], fail_silently=False)
        return JsonResponse({'mail': 'Successfully sent'}, status=200)
    except Exception:
        return JsonResponse({'mail': 'Something was wrong'}, status=404)


def password_email_request(request):
    if request.method == 'POST':
        password_form = PasswordResetForm(request.POST)
        if password_form.is_valid():
            current_site = get_current_site(request)

            data = password_form.cleaned_data['email']
            user_email = get_user_model().objects.filter(Q(email=data))

            if user_email.exists():
                for user in user_email:
                    subject = 'Password Request'
                    email_template_name = 'registration/password_reset_email.txt'
                    parameters = {
                        'email': user.email,
                        'domain': current_site.domain,
                        'site_name': 'Finum',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, parameters)
                    try:
                        send_mail(subject, email, 'hello@finum.online', [user.email], fail_silently=False)
                    except:
                        return HttpResponse('Invalid Header')
                    return redirect('password_reset_done')
            else:
                password_form.errors['email_404'] = 'Email not found'
    else:
        password_form = PasswordResetForm()

    context = {
        'password': password_form
    }

    return render(request, 'registration/password_reset_form.html', context)


@login_required(login_url='/signin/')
def deactivate_user(request):
    user = request.user
    user.is_active = False
    user.save()
    return redirect('dashboard:dashboard')


def email_invalid(request):
    return render(request, 'registration/email_send_invalid.html')


def email_send_success(request):
    return render(request, 'registration/email_send_success.html')


def bad_request(request):
    return render(request, 'registration/bad_request.html')

templates/customuser/signin.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load static i18n %}
<html lang="en">
	<!--begin::Head-->
	<head><base href="../../../">
		<title>Finum automatically imports payment data from banks, payment services, sales data from CRM, marketplaces,
			online stores into a single service and generates reports for analyzing business finances.</title>
		<meta charset="utf-8" />

		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="article" />
		<meta property="og:site_name" content="Finum" />
		<!--begin::Fonts-->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9/font/bootstrap-icons.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
		<!--end::Fonts-->
		<!--begin::Global Stylesheets Bundle(used by all pages)-->
		<link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Global Stylesheets Bundle-->
	</head>
	<!--end::Head-->
	<!--begin::Body-->
	<body data-kt-name="metronic" id="kt_body" class="app-blank app-blank bgi-size-cover bgi-position-center bgi-no-repeat">
		<!--begin::Root-->
		<div class="d-flex flex-column flex-root" id="kt_app_root">
			<style>body { background-image: url('{% static 'images/auth/bk.jpeg' %}'); }</style>

			<!--begin::Page bg image-->
			<!--end::Page bg image-->
			<!--begin::Authentication - Sign-in -->
			<div class="d-flex flex-column flex-lg-row flex-column-fluid">

				<!--begin::Body-->
				<div class="d-flex flex-column-fluid flex-lg-row-auto justify-content-center justify-content-lg-end p-12">
					<!--begin::Wrapper-->
					<div class="bg-body d-flex flex-center rounded-4 w-md-600px p-10 d_flex_wrap">
					<img class="theme-light-show mx-auto mw-100 w-150px w-lg-300px mb-10 mb-lg-20 logo_finum" src="{% static 'images/auth/finum_logo.png' %}" alt="" />

						<!--begin::Content-->
						<div class="w-md-400px">
							<!--begin::Form-->
							<form class="form w-100" id="kt_sign_in_form" action="" method="POST">
								{% csrf_token %}
								<!--begin::Heading-->
								<div class="text-center mb-11">
									<!--begin::Title-->
									<h1 class="text-dark fw-bolder mb-3">{% trans "Sign In" %}</h1>
									<!--end::Title-->
									<!--begin::Subtitle-->
									<div class="text-gray-500 fw-semibold fs-6">{% trans "Full access for 14 days. No credit card required." %}</div>
									<!--end::Subtitle=-->
								</div>
								<!--begin::Heading-->
								<!--begin::Login options-->
								<!--end::Login options-->

								<!--begin::Input group=-->
								<div class="fv-row mb-8">
									<!--begin::Email-->
									<div class="errors_div">
									{{ form.errors.email }}
									</div>
									<input required type="text" placeholder="{% trans 'Email' %}" name="email" autocomplete="off" class="form-control bg-transparent" />
									<!--end::Email-->
								</div>
								<!--end::Input group=-->
								<div class="fv-row mb-8" data-kt-password-meter="true">
									<!--begin::Wrapper-->
									<div class="mb-1">
										<!--begin::Input wrapper-->
										<div class="errors_div">
										{{ form.errors.password }}
										</div>
										<div class="position-relative mb-3">
											<input required class="pas form-control bg-transparent" type="password"  placeholder="{% trans 'Password' %}" name="password" id="password">
											<span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2 password-control" data-kt-password-meter-control="visibility">
												<i class="bi bi-eye-slash fs-2"></i>
												<i class="bi bi-eye fs-2 d-none"></i>
											</span>

										</div>
										<!--end::Input wrapper-->
									</div>
									<!--end::Wrapper-->
								</div>
								<!--end::Input group=-->
								<!--begin::Wrapper-->
								<div class="d-flex flex-stack flex-wrap gap-3 fs-base fw-semibold mb-8">
									<div></div>
									<!--begin::Link-->
									<a href="{% url 'password_reset' %}" class="link-primary">{% trans "Forgot Password" %} ?</a>
									<!--end::Link-->
								</div>
								<!--end::Wrapper-->
								<!--begin::Submit button-->
								<div class="d-grid mb-10">
									<button type="submit" id="kt_sign_in_submit" class="btn btn-primary">
										<!--begin::Indicator label-->
										<span class="indicator-label">{% trans "Sign In" %}</span>
										<!--end::Indicator label-->
										<!--begin::Indicator progress-->
										<span class="indicator-progress">{% trans "Please wait" %}...
										<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
										<!--end::Indicator progress-->
									</button>
								</div>
								<!--end::Submit button-->
								<!--begin::Sign up-->
								<div class="text-gray-500 text-center fw-semibold fs-6">{% trans "Not a Member yet" %}?
								<a href="{% url 'customuser:signup' %}" class="link-primary">{% trans "Sign up" %}</a></div>
								<!--end::Sign up-->
							</form>
							<!--end::Form-->
						</div>
						<!--end::Content-->
					</div>
					<!--end::Wrapper-->
				</div>
				<!--end::Body-->
			</div>
			<!--end::Authentication - Sign-in-->
		</div>
		<!--end::Root-->
		<!--begin::Javascript-->
		<script>var hostUrl = "static/";</script>
		<!--begin::Global Javascript Bundle(used by all pages)-->
		<script src="{% static 'plugins/global/plugins.bundle.js' %}"></script>
		<script src="{% static 'js/scripts.bundle.js' %}"></script>
		<!--end::Global Javascript Bundle-->
		<!--begin::Custom Javascript(used by this page)-->
		<script src="{% static 'js/custom/authentication/sign-in/general.js' %}"></script>
		<script src="https://snipp.ru/cdn/jquery/2.1.1/jquery.min.js"></script>
		<script>
		$('body').on('click', '.password-control', function(){
			if ($(this).hasClass('view')){
				$(this).removeClass('view');
				$('input.pas[type=text]').attr('type', 'password');
				$('.form-control').focus();
			} else {
				$(this).addClass('view');
				$('input.pas[type=password]').attr('type', 'text');
				$('.form-control').focus();
			}
			return false;
		});
		</script>
		<!--end::Custom Javascript-->
		<!--end::Javascript-->
	</body>
	<!--end::Body-->
</html>

templates/customuser/signup.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load static i18n %}

<html lang="en">
	<!--begin::Head-->
	<head>
		<title>Finum automatically imports payment data from banks, payment services, sales data from CRM, marketplaces,
			online stores into a single service and generates reports for analyzing business finances.</title>
		<meta charset="utf-8" />

		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="article" />
		<meta property="og:site_name" content="Finum" />
		<!--begin::Fonts-->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9/font/bootstrap-icons.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
		<!--end::Fonts-->
		<!--begin::Global Stylesheets Bundle(used by all pages)-->
		<link href="{% static 'plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Global Stylesheets Bundle-->
	</head>
	<!--end::Head-->
	<!--begin::Body-->
	<body data-kt-name="metronic" id="kt_body" class="app-blank app-blank bgi-size-cover bgi-position-center bgi-no-repeat">
		<!--begin::Root-->
		<div class="d-flex flex-column flex-root" id="kt_app_root">
			<!--begin::Page bg image-->

			<style>body { background-image: url('{% static 'images/auth/bk.jpeg' %}'); }</style>
			<!--end::Page bg image-->
			<!--begin::Authentication - Sign-up -->
			<div class="d-flex flex-column flex-lg-row flex-column-fluid">

				<!--begin::Body-->
				<div class="d-flex flex-column-fluid flex-lg-row-auto justify-content-center justify-content-lg-end p-12">
					<!--begin::Wrapper-->
					<div class="bg-body d-flex flex-center rounded-4 w-md-600px p-10 d_flex_wrap">
						<img class="theme-light-show mx-auto mw-100 w-150px w-lg-300px mb-10 mb-lg-20 logo_finum" src="{% static 'images/auth/finum_logo.png' %}" alt="" />

						<!--begin::Content-->
						<div class="w-md-400px">
							<!--begin::Form-->
							<form class="form w-100" novalidate="novalidate" id="kt_sign_up_form" action="" method="post">
								{% csrf_token %}
								<!--begin::Heading-->
								<div class="text-center mb-11">
									<!--begin::Title-->
									<h1 class="text-dark fw-bolder mb-3">{% trans "Sign Up" %}</h1>
									<!--end::Title-->
									<!--begin::Subtitle-->
									<div class="text-gray-500 fw-semibold fs-6">{% trans "Full access for 14 days. No credit card required." %}</div>
									<!--end::Subtitle=-->
								</div>
								<!--begin::Heading-->

								<!--begin::Input group=-->
								<div class="fv-row mb-8">
									<!--begin::Email-->
									<div class="errors_div">
										{{ form.errors.email }}
									</div>
									<input class="form-control bg-transparent" placeholder="{% trans 'Email' %}"  type="email" name="email" maxlength="254" id="id_email" autocomplete="off" autofocus required>
										<!--end::Email-->
								</div>
								<!--begin::Input group-->
								<div class="fv-row mb-8" data-kt-password-meter="true">
									<!--begin::Wrapper-->
									<div class="mb-1">
										<!--begin::Input wrapper-->
											<div class="errors_div">{{ form.errors.password1 }}</div>

										<div class="position-relative mb-3" >
											<input class="pas form-control bg-transparent " type="password"  placeholder="{% trans 'Password' %}" name="password1" id="password1" autocomplete="off">
											<span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2 password-control" data-kt-password-meter-control="visibility">
												<i class="bi bi-eye-slash fs-2"></i>
												<i class="bi bi-eye fs-2 d-none"></i>
											</span>
										</div>
										<!--end::Input wrapper-->
										<!--begin::Meter-->
										<div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
											<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
											<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
											<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
											<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
										</div>
										<!--end::Meter-->
									</div>
									<!--end::Wrapper-->
									<!--begin::Hint-->
									<div class="text-muted">{% trans "Use 8 or more characters with a mix of letters, numbers &amp; symbols." %}</div>
									<!--end::Hint-->
								</div>
								<!--end::Input group=-->
								<!--end::Input group=-->
								<div class="fv-row mb-8" data-kt-password-meter="true">
									<!--begin::Wrapper-->
									<div class="mb-1">
										<!--begin::Input wrapper-->
										<div class="errors_div">
										{{ errors.password2 }}
										</div>
										<div class="position-relative mb-3">
											<input class="pas form-control bg-transparent" type="password"  placeholder="{% trans 'Password' %}" name="password2" id="password2" autocomplete="off">
										</div>
										<input class="my_custom_form" type="password"  placeholder="{% trans 'Password' %}" name="password3" id="password3" autocomplete="off">

										<!--end::Input wrapper-->
									</div>
									<!--end::Wrapper-->
								</div>
								<!--end::Input group=-->

								<!--begin::Submit button-->
								<div class="d-grid mb-10">
									<button type="submit" id="kt_sign_up_submit" class="btn btn-primary">
										<!--begin::Indicator label-->
										<span class="indicator-label">{% trans "Sign up" %}</span>
										<!--end::Indicator label-->
										<!--begin::Indicator progress-->
										<span class="indicator-progress">{% trans "Please wait" %}...
										<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
										<!--end::Indicator progress-->
									</button>
								</div>
								<!--end::Submit button-->
								<!--begin::Sign up-->
								<div class="text-gray-500 text-center fw-semibold fs-6">{% trans "Already have an Account" %}?
								<a href="{% url 'customuser:signin' %}" class="link-primary fw-semibold">{% trans "Sign in" %}</a></div>

								<!--end::Sign up-->
							</form>
							<!--end::Form-->
						</div>
						<!--end::Content-->
					</div>
					<!--end::Wrapper-->
				</div>
				<!--end::Body-->
			</div>
			<!--end::Authentication - Sign-up-->
		</div>
		<!--end::Root-->
		<!--begin::Javascript-->
		<!--begin::Global Javascript Bundle(used by all pages)-->
		<script src="{% static 'plugins/global/plugins.bundle.js' %}"></script>
		<script src="{% static 'js/scripts.bundle.js' %}"></script>
		<!--end::Global Javascript Bundle-->
		<!--begin::Custom Javascript(used by this page)-->
		<script src="{% static 'js/custom/authentication/sign-up/general.js' %}"></script>
		<!--end::Custom Javascript-->
		<!--end::Javascript-->
		<script>
			$('body').on('click', '.password-control', function(){
				if ($(this).hasClass('view')){
					$(this).removeClass('view');
					$('input.pas[type=text]').attr('type', 'password');
					$('.form-control').focus();
				} else {
					$(this).addClass('view');
					$('input.pas[type=password]').attr('type', 'text');
					$('.form-control').focus();
				}
				return false;
			});
			</script>
	</body>


</html>