core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from customuser.views import password_email_request
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('user/password_reset/', password_email_request, name='password_reset'),
    path('user/', include('django.contrib.auth.urls')),
    path('', include('customuser.urls', namespace='customuser')),
    path('', include('company.urls', namespace='company')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('transactions.urls', namespace='transactions')),
    path('', include('orders.urls', namespace='orders')),
    path('', include('contractors.urls', namespace='contractors')),
    path('', include('subscription.urls', namespace='subscription')),
    path('', include('dashboard.urls', namespace='dashboard')),
    path('', include('products.urls', namespace='products')),
    path('', include('invoice.urls', namespace='invoice')),
    path('', include('integrations.urls', namespace='integrations')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import products, add_product, delete_product, product_edit, delete_item, delete_invItem

app_name = 'products'

urlpatterns = [
    path('products/', products, name='products'),
    path('add_product/', add_product, name='add_product'),
    path('delete_product/', delete_product, name='delete_product'),
    path('product/<uuid:prod_uid>/', product_edit, name='product_edit'),
    path('products/delete_item/', delete_item, name='delete_item'),
    path('product/delete_invoice_item', delete_invItem, name='delete_invItem'),
]

products/models.py
from django.db import models
from customuser.models import User_Account
import uuid
from orders.models import Order


class Product(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user_account = models.ForeignKey(User_Account, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=255, blank=False, null=False, unique=True)
    product_price = models.DecimalField(decimal_places=2, max_digits=30)
    currency = models.CharField(max_length=3)

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'



class OrderItem(models.Model):
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user_account = models.ForeignKey(User_Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='products')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    price = models.DecimalField(decimal_places=2, max_digits=30)
    quantity = models.IntegerField()


    def __str__(self):
        return f'{self.product} + {self.quantity} + {self.order}'

    class Meta:
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'

products/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from company.models import Currency
from invoice.models import InvoiceItem
from orders.models import Order
from .models import Product, OrderItem
from customuser.models import User_Account
from invoice.models import Invoice
from django.contrib.auth.decorators import login_required


@login_required(login_url='/signin/')
def products(request):
    user_account = User_Account.objects.get(owner=request.user)

    products = Product.objects.filter(user_account=user_account)
    currencies = Currency.objects.all()
    return render(request, 'products/products.html', {'currencies': currencies, 'products': products})


@login_required(login_url='/signin/')
def add_product(request):
    if request.method == 'POST':
        product_name = request.POST.get('product_name')
        product_cost = request.POST.get('product_cost')
        currency_name = request.POST.get('currency_name')

        user_account = User_Account.objects.get(owner=request.user)

        new_product = Product.objects.create(product_name=product_name, product_price=product_cost,
                                             currency=currency_name, user_account=user_account)
        return redirect('products:products')


@login_required(login_url='/signin/')
def delete_product(request):
    user_account = User_Account.objects.get(owner=request.user)
    prod_uid = request.POST.get('uid')

    if user_account:
        product = Product.objects.filter(user_account=user_account, uid=prod_uid)
        product.delete()
        return redirect('products:products')


@login_required(login_url='/signin/')
def product_edit(request, prod_uid):
    user_account = User_Account.objects.get(owner=request.user)
    currencies = Currency.objects.all()
    product = Product.objects.filter(user_account=user_account, uid=prod_uid)
    context = {'product': product[0], 'currencies': currencies}

    if request.method == 'POST':
        product_name = request.POST.get('product_name')
        product_cost = request.POST.get('product_cost')
        currency = request.POST.get('currency_name')

        product_price = product_cost.replace(',', '.')

        try:
            float(product_price)
        except ValueError:
            context['price_error'] = 'Please, enter the number value'
            return render(request, 'products/product_edit.html', context)

        product.update(product_name=product_name, product_price=product_price, currency=currency)

        return HttpResponseRedirect(f'/product/{prod_uid}/')
    else:
        return render(request, 'products/product_edit.html', context)


@login_required(login_url='/signin/')
def delete_item(request):
    user_account = User_Account.objects.get(owner=request.user)
    if user_account:
        uid = request.POST.get('id')
        order_uid = request.POST.get('order_uid')
        order_item = OrderItem.objects.get(uid=uid)
        order = Order.objects.get(user=user_account, uid=order_uid)
        new_total = float(order.order_sum) - float(order_item.price) * int(order_item.quantity)
        order.order_sum = new_total
        order.save()
        order_item.delete()
        return JsonResponse({}, status=200)


@login_required(login_url='/signin/')
def delete_invItem(request):
    user_account = User_Account.objects.get(owner=request.user)
    if user_account:
        uid = request.POST.get('id')
        invoice_uid = request.POST.get('invoice_uid')
        invoice_item = InvoiceItem.objects.get(uid=uid)
        invoice = Invoice.objects.get(user_account=user_account, uid=invoice_uid)
        new_total = float(invoice.invoice_sum) - float(invoice_item.price) * int(invoice_item.quantity)
        invoice.invoice_sum = new_total
        invoice.save()
        invoice_item.delete()
        return JsonResponse({}, status=200)

templates/products/product_edit.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load static i18n %}

{% block nav_product %}
    here
{% endblock nav_product %}

{% block head %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" />
{% endblock head %}

{% block content %}
<!--begin::Main-->
<!--begin::Content wrapper-->
<div class="d-flex flex-column flex-column-fluid">
	<!--begin::Toolbar-->

	<div class="app-toolbar py-3 py-lg-6">
		<!--begin::Toolbar container-->
		<div class="app-container container-xxl d-flex flex-stack">
			<!--begin::Page title-->
			<div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
				<!--begin::Title-->
				<h1 class="page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0">{% trans "Product Settings" %}</h1>
				<!--end::Title-->
				<!--begin::Breadcrumb-->
				<ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">

					<!--begin::Item-->
					<li class="breadcrumb-item text-muted">
						<a href="{% url 'products:products' %}" class="text-muted text-hover-primary">{% trans "Products" %}</a>
					</li>
					<!--end::Item-->
										<!--begin::Item-->
					<li class="breadcrumb-item">
						<span class="bullet bg-gray-400 w-5px h-2px"></span>
					</li>
					<!--end::Item-->
					<!--begin::Item-->
					<li class="breadcrumb-item text-muted">{{ product.product_name }}</li>
					<!--end::Item-->
				</ul>
				<!--end::Breadcrumb-->
			</div>
			<!--end::Page title-->
		</div>
		<!--end::Toolbar container-->
	</div>
	<!--end::Toolbar-->
	<!--begin::Content-->
	<div class="app-content flex-column-fluid">
		<!--begin::Content container-->
		<div class="app-container container-xxl">
			<!--begin::Navbar-->
			<div class="card mb-5 mb-xl-10">
				<div class="card-body pt-9 pb-0">
					<!--begin::Details-->
					<div class="d-flex flex-wrap flex-sm-nowrap mb-3">

						<!--begin::Info-->
						<div class="flex-grow-1">
							<!--begin::Title-->
							<div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
								<!--begin::User-->
								<div class="d-flex flex-column">
									<!--begin::Name-->
									<div class="d-flex align-items-center mb-2">
										<a href="#" class="text-gray-900 text-hover-primary fs-2 fw-bold me-1">
												{% trans "Change your product settings" %}
										</a>
										<a>
											<!--begin::Svg Icon | path: icons/duotune/general/gen026.svg-->
											<span class="svg-icon svg-icon-1 svg-icon-primary">
												<svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24">
													<path d="M10.0813 3.7242C10.8849 2.16438 13.1151 2.16438 13.9187 3.7242V3.7242C14.4016 4.66147 15.4909 5.1127 16.4951 4.79139V4.79139C18.1663 4.25668 19.7433 5.83365 19.2086 7.50485V7.50485C18.8873 8.50905 19.3385 9.59842 20.2758 10.0813V10.0813C21.8356 10.8849 21.8356 13.1151 20.2758 13.9187V13.9187C19.3385 14.4016 18.8873 15.491 19.2086 16.4951V16.4951C19.7433 18.1663 18.1663 19.7433 16.4951 19.2086V19.2086C15.491 18.8873 14.4016 19.3385 13.9187 20.2758V20.2758C13.1151 21.8356 10.8849 21.8356 10.0813 20.2758V20.2758C9.59842 19.3385 8.50905 18.8873 7.50485 19.2086V19.2086C5.83365 19.7433 4.25668 18.1663 4.79139 16.4951V16.4951C5.1127 15.491 4.66147 14.4016 3.7242 13.9187V13.9187C2.16438 13.1151 2.16438 10.8849 3.7242 10.0813V10.0813C4.66147 9.59842 5.1127 8.50905 4.79139 7.50485V7.50485C4.25668 5.83365 5.83365 4.25668 7.50485 4.79139V4.79139C8.50905 5.1127 9.59842 4.66147 10.0813 3.7242V3.7242Z" fill="currentColor" />
													<path d="M14.8563 9.1903C15.0606 8.94984 15.3771 8.9385 15.6175 9.14289C15.858 9.34728 15.8229 9.66433 15.6185 9.9048L11.863 14.6558C11.6554 14.9001 11.2876 14.9258 11.048 14.7128L8.47656 12.4271C8.24068 12.2174 8.21944 11.8563 8.42911 11.6204C8.63877 11.3845 8.99996 11.3633 9.23583 11.5729L11.3706 13.4705L14.8563 9.1903Z" fill="white" />
												</svg>
											</span>
											<!--end::Svg Icon-->
										</a>
									</div>
									<!--end::Name-->

								</div>
								<!--end::User-->

							</div>
							<!--end::Title-->
							<!--begin::Stats-->
							<div class="d-flex flex-wrap flex-stack">

							</div>
							<!--end::Stats-->
						</div>
						<!--end::Info-->
					</div>
					<!--end::Details-->
				</div>
			</div>
			<!--end::Navbar-->
			<!--begin::Basic info-->
			<div class="card mb-5 mb-xl-10">
				<!--begin::Card header-->
				<div class="card-header border-0 cursor-pointer" role="button" data-bs-toggle="collapse" data-bs-target="#kt_account_profile_details" aria-expanded="true" aria-controls="kt_account_profile_details">
					<!--begin::Card title-->
					<div class="card-title m-0">
						<h3 class="fw-bold m-0">{% trans "Product Details" %}</h3>
					</div>
					<!--end::Card title-->
				</div>
				<!--begin::Card header-->
				<!--begin::Content-->
				<div id="kt_account_settings_profile_details" class="collapse show">
					<!--begin::Form-->
					<form id="kt_account_profile_details_form" class="form" method="post" action="{% url 'products:product_edit' prod_uid=product.uid %}">
						{% csrf_token %}
						<!--begin::Card body-->
						<div class="card-body border-top p-9">

							<!--begin::Input group-->
							<div class="row mb-6">
								<!--begin::Label-->
								<label class="col-lg-4 col-form-label fw-semibold fs-6">
									<span>{% trans "Product name" %}</span>
								</label>
								<!--end::Label-->
								<!--begin::Col-->
								<div class="col-lg-8 fv-row">
									<input type="tel" name="product_name" class="form-control form-control-lg form-control-solid" placeholder="{% trans 'Contractor name' %}" value="{{ product.product_name }}"/>
								</div>
								<!--end::Col-->
							</div>
							<!--end::Input group-->
							<!--begin::Input group-->
							<div class="row mb-6">
								<!--begin::Label-->
								<label class="col-lg-4 col-form-label fw-semibold fs-6">
									<span>{% trans "Product price" %}</span>
								</label>
								<!--end::Label-->
								<!--begin::Col-->
								<div class="col-lg-8 fv-row">
									<div class="errorlist">{{ price_error }}</div>
									<input name="product_cost" class="form-control form-control-lg form-control-solid" placeholder="{% trans 'Product price' %}" value="{{ product.product_price|safe }}" onkeypress="if ( isNaN(this.value + String.fromCharCode(event.keyCode) )) return false;"/>
								</div>
								<!--end::Col-->
							</div>
							<!--end::Input group-->
							<div class="row mb-6">
														<!--begin::Label-->
                                    <label class="col-lg-4 col-form-label fw-semibold fs-">{% trans "Select your Currency" %}</label>
                                    <!--end::Label-->
                                    <!--begin::Input-->
                                    <div class="col-lg-8 fv-row ">
                                        <select class="js-example-basic-multiple form-select form-select-solid form-select-lg select2-hidden-accessible" id="select_currency" name="currency_name">
                                        {% for currency in currencies %}
                                            {% if product.currency == currency.currency %}
                                                <option value="{{ currency }}" selected>{{ currency }}</option>
                                            {% else %}
                                                <option value="{{ currency }}">{{ currency }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
												</div>
                                    <!--end::Input-->
													</div>

						</div>
						<!--end::Card body-->
						<!--begin::Actions-->
						<div class="card-footer d-flex justify-content-end py-6 px-9">
							<button type="reset" class="btn btn-light btn-active-light-primary me-2">{% trans "Discard" %}</button>
							<button type="submit" class="btn btn-primary" id="kt_account_profile_details_submit">{% trans "Save Changes" %}</button>
						</div>
						<!--end::Actions-->
					</form>
					<!--end::Form-->
				</div>
				<!--end::Content-->
			</div>

		</div>
		<!--end::Content container-->
	</div>
	<!--end::Content-->
</div>
<!--end:::Main-->
{% endblock content %}

{% block scripts %}
		<script>var hostUrl = "static/";</script>
		<!--begin::Custom Javascript(used by this page)-->
		<script src="{% static 'js/custom/apps/customers/list/export.js'%}"></script>
		<script src="{% static 'js/custom/apps/customers/list/list.js'%}"></script>
		<script src="{% static 'js/custom/apps/customers/add.js' %}"></script>
		<script src="{% static 'js/widgets.bundle.js' %}"></script>
		<script src="{% static 'js/custom/widgets.js' %}"></script>
		<script src="{% static 'js/custom/apps/chat/chat.js'%}"></script>
		<script src="{% static 'js/custom/utilities/modals/upgrade-plan.js' %}s"></script>
		<script src="{% static 'js/custom/utilities/modals/create-app.js' %}"></script>
		<script src="{% static 'js/custom/utilities/modals/users-search.js' %}"></script>
		<script>
			$(document).ready(function() {
			$('#select_currency').select2({tags: false, minimumResultsForSearch: -1, dropdownParent: $("#select_currency").parent()});
		});
		</script>
{% endblock scripts %}